import { Poppins } from "next/font/google";
import Header from "../components/header.js";
import "./globals.css";
import Return from '../components/return.js';

const poppins = Poppins({ subsets: ["latin"], weight:["100", "200", "300", "400", "500", "600", "700", "800", "900"] });

export const metadata = {
  title: "testApp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />
        <div className="container max-w-[1494px] mx-auto">
          <Return text="ВЕРНУТЬСЯ К СОТРУДНИКАМ" />
          {children}
        </div>
      </body>
    </html>
  );
}